CREATE TABLE FATURAMENTO(
	id INT IDENTITY(1,1) PRIMARY KEY,
	dataCompra DATE,
	ValorAtual MONEY
	)

ALTER TRIGGER ValoresAtualizados
ON [ITENS NOTAS FISCAIS]
AFTER INSERT 
AS
BEGIN
	DECLARE @soma MONEY
	SELECT @soma = SUM(PREÇO*QUANTIDADE) FROM [ITENS NOTAS FISCAIS]
	INSERT INTO FATURAMENTO VALUES (GETDATE(), @soma)
END

INSERT [dbo].[ITENS NOTAS FISCAIS] ([NUMERO], [CODIGO DO PRODUTO], [QUANTIDADE], [PREÇO]) VALUES (100, N'1000889', 63, 24.01)
SELECT * FROM [ITENS NOTAS FISCAIS]
SELECT * FROM FATURAMENTO
