
-- FAÇA UM SELECT USANDO ALGUMA VARIAÇÃO DO JOIN
-- PARA DESCOBRIR QUEM É O CLIENTE QUE NÃO TEM NOTA FISCAL
-- USE AS TABELAS 'TABELA DE CLIENTE' E 'NOTAS FISCAIS'
-- USE UM GROUP BY PARA AGRUPAR AS NOTAS

-- RESOLUÇÃO1
select c.nome, count(nf.CPF) as 'quantidade'
from [TABELA DE CLIENTES]c LEFT join [NOTAS FISCAIS]nf
on c.CPF = nf.CPF
group by c.NOME

--RESOLUÇÃO2
select c.nome, NF.CPF
from [TABELA DE CLIENTES]c LEFT join [NOTAS FISCAIS]nf
on c.CPF = nf.CPF
WHERE nf.CPF IS NULL





-- EXEMPLO DE SUBSELECT NA CLAUSULA WHERE
SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES]
WHERE BAIRRO IN (SELECT BAIRRO FROM [TABELA DE VENDEDORES])

-- EXEMPLO DE SUBSELECT NO FROM
SELECT NOVA_CONSULTA.EMBALAGEM, NOVA_CONSULTA.MAX_PRECO
FROM (
SELECT EMBALAGEM, MAX([PREÇO DE LISTA])AS MAX_PRECO
FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM) NOVA_CONSULTA
WHERE NOVA_CONSULTA.MAX_PRECO <=5

--exemplo de union
select v.BAIRRO from [TABELA DE VENDEDORES] v
union
select c.BAIRRO from [TABELA DE CLIENTES] c

--o union aplica o 'distinct por padrão,
-- para mostrar todos os valores use o union all
select v.BAIRRO from [TABELA DE VENDEDORES] v
union all
select c.BAIRRO from [TABELA DE CLIENTES] c













